name: Redirect circleci artifacts

on: [status]
jobs:
  circleci_artifacts_redirector_job:
    runs-on: ubuntu-22.04
    if: >
      github.repository == 'scipy/scipy'
      && github.event.context == 'ci/circleci: build_docs'
    name: Run CircleCI artifacts redirector
    steps:
      - restore_cache:
          keys:
            - -{{ checksum "doc/Makefile" }}-
      - save_cache:
          key: -{{ checksum "doc/Makefile" }}-
          paths:
            - source/_contents
      - name: GitHub Action step
        uses: larsoner/circleci-artifacts-redirector-action@master
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          api-token: ${{ secrets.CIRCLE_TOKEN }}
          artifact-path: 0/html/index.html
          circleci-jobs: build_docs
          job-title: Check the rendered docs here!
