name: Windows tests (MSVC + ifx + OpenBLAS)

on:
  push:
    branches:
      - maintenance/**
  pull_request:
    branches:
      - main
      - maintenance/**

permissions:
   contents: read  # to fetch code (actions/checkout)

env:
  WINDOWS_BASEKIT_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/7dff44ba-e3af-4448-841c-0d616c8da6e7/w_BaseKit_p_2024.1.0.595_offline.exe
  WINDOWS_HPC_URL: https://registrationcenter-download.intel.com/akdlm/IRC_NAS/c95a3b26-fc45-496c-833b-df08b10297b9/w_HPCKit_p_2024.1.0.561_offline.exe
  SAMPLES_TAG: 2024.1.0
  COMPILER_VERSION: 2024.1.0
  TBB_VERSION: 2021.12.0
  VS_VER: vs2022

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  get_commit_message:
    name: Get commit message
    uses: ./.github/workflows/commit_message.yml

  fast_dev_py_fail_slow:
    name: fail slow, fast, py3.12/npAny, dev.py
    needs: get_commit_message
    # Ensure (a) this doesn't run on forks by default, and
    #        (b) it does run with Act locally (`github` doesn't exist there)
    if: >
      needs.get_commit_message.outputs.message == 1
      && (github.repository == 'czgdp1807/scipy' || github.repository == '')
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          submodules: recursive

      - name: Setup conda
        uses: s-weigand/setup-conda@v1
        with:
          update-conda: true
          python-version: 3.11
      - run: conda --version
      - run: which python

      - name: Install pkg-config
        run: |
          conda install -c conda-forge pkg-config meson meson-python ninja

      - name: pip-packages
        run: |
          pip install numpy==1.23.5 cython pybind11 pytest pytest-xdist pytest-timeout pytest-fail-slow pooch rich_click click doit pydevtool hypothesis
          pip install -r requirements/openblas.txt

      - name: cache install
        id: cache-install
        uses: actions/cache@v3
        with:
          path: |
              C:\Program Files (x86)\Intel\
          key: install-${{ env.WINDOWS_HPC_URL }}-${{ env.WINDOWS_BASEKIT_URL }}-compiler
      - name: Install oneAPI Base kit
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: |
          echo %WINDOWS_BASEKIT_URL%
          tools/install_intel_oneAPI_windows.bat %WINDOWS_BASEKIT_URL%
      - name: Install oneAPI HPC kit
        if: steps.cache-install.outputs.cache-hit != 'true'
        run: |
          echo %WINDOWS_HPC_URL%
          tools/install_intel_oneAPI_windows.bat %WINDOWS_HPC_URL%
      - name: Initialise Intel oneAPI
        run: |
          C:\"Program Files (x86)"\Intel\oneAPI\setvars.bat

      - name: Set PATH
        run: setx /M PATH "C:\Program Files (x86)\Intel\oneAPI\tbb\latest\env\..\bin\\;C:\Program Files (x86)\Intel\oneAPI\ocloc\latest\bin;C:\Program Files (x86)\Intel\oneAPI\mpi\latest\env\\..\opt\mpi\libfabric\bin;C:\Program Files (x86)\Intel\oneAPI\mpi\latest\env\\..\bin;C:\Program Files (x86)\Intel\oneAPI\mkl\latest\bin;C:\Program Files (x86)\Intel\oneAPI\ippcp\latest\bin;C:\Program Files (x86)\Intel\oneAPI\ipp\latest\bin;C:\Program Files (x86)\Intel\oneAPI\dpcpp-ct\latest\env\..\bin;C:\Program Files (x86)\Intel\oneAPI\dnnl\latest\env\..\bin;C:\Program Files (x86)\Intel\oneAPI\dev-utilities\latest\bin;C:\Program Files (x86)\Intel\oneAPI\debugger\latest\env\\..\opt\debugger\bin;C:\Program Files (x86)\Intel\oneAPI\dal\latest\bin;C:\Program Files (x86)\Intel\oneAPI\compiler\latest\lib\ocloc;C:\Program Files (x86)\Intel\oneAPI\compiler\latest\bin;C:\Program Files (x86)\Intel\oneAPI\compiler\latest\opt\oclfpga\host\windows64\bin;C:\Program Files (x86)\Intel\oneAPI\compiler\latest\opt\oclfpga\bin;%PATH%"

      - name: Refresh cmd
        run: RefreshEnv.cmd

      - name: Print PATH
        run: echo %PATH%

      # - name: Build
      #   run: |
      #     set FC=C:\'Program Files (x86)'\Intel\oneAPI\2024.1\bin\ifx.exe
      #     python dev.py build -C-Duse-pythran=false -C--vsenv --with-scipy-openblas
